package biblioteca;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DEVOLUCION extends javax.swing.JFrame {

    DefaultTableModel mdprestamo;
    List<Listas.Prestamo> Lis_pres;
    List<Listas.DiasPermitidos> Lis_Dias;
    List<Listas.ValorLibro>Lis_Valor;
    String data[][] = {};
    String Cabeza[] = {"ID PRESTAMO", "ID LIBRO", "ID USUARIO", "FECHA PRESTAMO", "FECHA DEVOLUCION"};
    Conexion.Conectar cc = new Conexion.Conectar();
    Connection cn = cc.conexion();

    public DEVOLUCION() {
        initComponents();
        mdprestamo = new DefaultTableModel(data, Cabeza) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table_devolucion.setModel(mdprestamo);
        llenar_pres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_devolucion = new javax.swing.JTable();
        jd_fecha = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(68, 44, 188));
        jButton2.setText("DEVOLVER LIBRO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 44, 188));
        jLabel5.setText("FECHA DE DEVOLUCIÓN");

        table_devolucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_devolucion);

        jButton3.setText("VOLVER AL MENU");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jd_fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 170, 820, 430));

        jPanel1.setBackground(new java.awt.Color(68, 44, 188));

        jLabel13.setFont(new java.awt.Font("Constantia", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DEVOLUCIÓN");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/20200601_175239_0000.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(44, 44, 44))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 800, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void llenar_pres() {

        Listas.Consultas obtn = new Listas.Consultas();
        Lis_pres = obtn.obtprestamocd();

        for (int i = 0; i < Lis_pres.size(); i++) {
            int id_prestamo = Lis_pres.get(i).getId_prestamo();
            String id_libro = Lis_pres.get(i).getId_libro();
            int id_usuario = Lis_pres.get(i).getId_usuario();
            String fecha_prestamo = Lis_pres.get(i).getFecha_prestamo();
            String fecha_devolucion = Lis_pres.get(i).getFecha_devolucion();
            Object datos[] = {id_prestamo, id_libro, id_usuario, fecha_prestamo, fecha_devolucion};
            mdprestamo.addRow(datos);

        }

    }

    public static Date ParseFecha(String fecha) {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;
        try {
            fechaDate = formato.parse(fecha);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        return fechaDate;
    }

    public void llenar_dias(String id_libro, int id_usuario) {
        Listas.Consultas obtn = new Listas.Consultas();
        Lis_Dias = obtn.obtDiaspermitidos(id_libro, id_usuario);

    }
    public void llenarValor(String id_libro) {
        Listas.Consultas obtn = new Listas.Consultas();
        Lis_Valor = obtn.obtVlibro(id_libro);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Date fecha_devolucion = jd_fecha.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/YYYY");
        String fecha_dev = sdf.format(fecha_devolucion);
        int x = table_devolucion.getSelectedRow();
        String fecha_prestamo = (String) table_devolucion.getValueAt(x, 3);

        int id_pres = Integer.parseInt(String.valueOf(table_devolucion.getValueAt(x, 0)));

        Date fecha_prest = ParseFecha(fecha_prestamo);
        int Dias_entrega = (int) (fecha_devolucion.getTime() - fecha_prest.getTime()) / 86400000;
        System.out.println(""+id_pres);

        System.out.println(""+Dias_entrega);
        String Consultasql = "UPDATE PRESTAMO  SET fecha_devolucion = '" +fecha_dev+ " 'WHERE id_prestamo = " +id_pres+ ";";
        try {
            PreparedStatement ps = cn.prepareStatement(Consultasql);
            JOptionPane.showMessageDialog(null, "EL LIBRO HA SIDO DEVUELTO");
            ps.execute();
        } catch (Exception e) {
            System.out.println(""+e);
        }

        String id_libro = (String) table_devolucion.getValueAt(x, 1);
        int id_usuario = Integer.parseInt(String.valueOf(table_devolucion.getValueAt(x, 2)));
        llenar_dias(id_libro, id_usuario);
        int DiasColeccion = Lis_Dias.get(0).getDiasColeccion();
        int DiasUsuario = Lis_Dias.get(0).getDiasUsuario();
        int DiasTotales = DiasUsuario + DiasColeccion;
        System.out.println("estos son los dias de entrega "+Dias_entrega);
        System.out.println("estos son los dias de totales permitidos "+DiasTotales);
        // int ValorLibro = Lis_Valor.get(0).getValorLibro();
        // System.out.println(""+ValorLibro);
        if (Dias_entrega > DiasTotales) {
            System.out.println("entro");
            int Dias_mora = Dias_entrega-DiasTotales;
            System.out.println("dias de mora"+Dias_mora);
            int valor_multa = (Dias_entrega-DiasTotales)*1000;
            System.out.println("valor_multa "+valor_multa);
            llenarValor(id_libro);
           int ValorLibro = Integer.parseInt(String.valueOf(Lis_Valor.get(0).getValorLibro()));
            System.out.println("el valor del libro"+ValorLibro);
            double costo = ValorLibro*1.10;
            System.out.println("ell valor de la multa"+valor_multa);
            System.out.println("el valor del 110 de libro es:"+costo);
            if(valor_multa>costo){
                System.out.println("entro xd jajaja");
            String MULTASQL = "INSERT INTO MULTA(id_usuario,id_prestamo,dia_mora,valor_multa) VALUES (?,?,?,?)";
            try {
                System.out.println("entro 2.0");
                PreparedStatement ps = cn.prepareStatement(MULTASQL);
                ps.setInt(1, id_usuario);
                ps.setInt(2, id_pres);
                ps.setInt(3, Dias_mora);
                ps.setInt(4, (int)(costo));
                
                ps.execute();
            } catch (Exception e) {
                System.out.println(""+e);
            }

        }else {
                System.out.println("ja entro");
             String MULTASQL = "INSERT INTO MULTA(id_usuario,id_prestamo,dia_mora,valor_multa) VALUES (?,?,?,?)";
            try {
                System.out.println("no mires aca que entro");           
                PreparedStatement ps = cn.prepareStatement(MULTASQL);
                ps.setInt(1, id_usuario);
                ps.setInt(2, id_pres);
                ps.setInt(3, Dias_mora);
                ps.setInt(4, valor_multa);
                
                ps.execute();
            } catch (Exception e) {
                System.out.println(""+e);
            }
            }
        }
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Principal in = new Principal();
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DEVOLUCION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DEVOLUCION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DEVOLUCION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DEVOLUCION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DEVOLUCION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jd_fecha;
    private javax.swing.JTable table_devolucion;
    // End of variables declaration//GEN-END:variables
}
